### ISSUE TITLE
Right display not shown up together with Left menu

### ISSUE THREAD

**Issue by kul1** [songrit/mindapp#23]
I installed all same version as required
Ruby 2.1.1 and rails 4.2.0
in Mac OSX 10.11.5

<img width="1022" alt="screen shot 2559-07-13 at 9 54 48 am" src="https://cloud.githubusercontent.com/assets/3953832/16790450/59efe588-48e0-11e6-9bf6-3236759c1d19.png">

**Comment by songrit** [comment]
Please upgrade to Rails 5 and install mindapp gem from github
