### ISSUE TITLE
Undefined error in admin edit user role.

### ISSUE THREAD

**Issue by la2135551212** [songrit/mindapp#26]
Admin can not edit user role. in 
-2.2.4@4.2.6
-2.3.3@4.2.8
-2.3.3@5

![screen shot 2560-02-13 at 5 08 08 pm](https://cloud.githubusercontent.com/assets/25674735/22879212/76e40556-f20f-11e6-8c21-eb65bce0a46d.png)

**Comment by kul1** [comment]
Fixed in branch a241510 and f241502
Considered Closed

**Comment by la2135551212** [comment]
Yes fixed in branch a241510 and f241502
